[2024-05-22T00:53:20.383+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T00:53:20.460+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-21T22:05:48.748499+00:00 [queued]>
[2024-05-22T00:53:20.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-21T22:05:48.748499+00:00 [queued]>
[2024-05-22T00:53:20.497+0000] {taskinstance.py:2306} INFO - Starting attempt 30 of 34
[2024-05-22T00:53:20.771+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-21 22:05:48.748499+00:00
[2024-05-22T00:53:20.786+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=239) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T00:53:20.789+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2024-05-22T00:53:20.788+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-21T22:05:48.748499+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpg8mhtbm8']
[2024-05-22T00:53:20.792+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask extraccion
[2024-05-22T00:53:20.920+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-21T22:05:48.748499+00:00 [running]> on host 5b8d782b22fb
[2024-05-22T00:53:21.175+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T22:05:48.748499+00:00' AIRFLOW_CTX_TRY_NUMBER='30' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T22:05:48.748499+00:00'
[2024-05-22T00:53:21.179+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T00:53:21.266+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-22T00:53:27.040+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T00:53:27.042+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kaggle_dataset.py", line 27, in extract_task
    subprocess.run("unzip global-economy-indicators.zip -d ./data", shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'unzip global-economy-indicators.zip -d ./data' returned non-zero exit status 127.
[2024-05-22T00:53:27.076+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-21T22:05:48.748499+00:00, execution_date=20240521T220548, start_date=20240522T005320, end_date=20240522T005327
[2024-05-22T00:53:27.111+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task extraccion (Command 'unzip global-economy-indicators.zip -d ./data' returned non-zero exit status 127.; 263)
[2024-05-22T00:53:27.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-22T00:53:27.210+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T00:53:27.215+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
