[2024-05-23T00:46:33.657+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T00:46:33.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-22T22:09:25.534916+00:00 [queued]>
[2024-05-23T00:46:33.708+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-22T22:09:25.534916+00:00 [queued]>
[2024-05-23T00:46:33.710+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 9
[2024-05-23T00:46:33.730+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-22 22:09:25.534916+00:00
[2024-05-23T00:46:33.741+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2993) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T00:46:33.743+0000] {standard_task_runner.py:63} INFO - Started process 3017 to run task
[2024-05-23T00:46:33.744+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'load', 'manual__2024-05-22T22:09:25.534916+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmp_ejftii7']
[2024-05-23T00:46:33.747+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask load
[2024-05-23T00:46:33.817+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.load manual__2024-05-22T22:09:25.534916+00:00 [running]> on host 3943db1ddae8
[2024-05-23T00:46:33.953+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T22:09:25.534916+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T22:09:25.534916+00:00'
[2024-05-23T00:46:33.957+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T00:46:33.985+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T00:46:33.986+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kaggle_dataset.py", line 67, in load_task
    df = transform_task()
         ^^^^^^^^^^^^^^^^
TypeError: 'PythonOperator' object is not callable
[2024-05-23T00:46:34.009+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_dataset, task_id=load, run_id=manual__2024-05-22T22:09:25.534916+00:00, execution_date=20240522T220925, start_date=20240523T004633, end_date=20240523T004634
[2024-05-23T00:46:34.029+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task load ('PythonOperator' object is not callable; 3017)
[2024-05-23T00:46:34.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T00:46:34.092+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-23T00:46:34.112+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T00:46:34.117+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
